# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27ed7c9499ba890725f8acdb38c7dc7076529fdb02d366b25107adecf9d7f2de2d1f93ad05f05d44859581594a06ce6e59f5cc91d30288cfb49c7df1fde7712c

test:
  secret_key_base: 09d2bc6fc8fa167695d676e9f6a13df450d7e240b945d1883c0325b73656515d952321ed567cdfd25e0d4b99bcc15ee586423ed064f74db8b2c1bc4125114e76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
